# This is a basic workflow to help you get started with Actions

name: AutoSubmit

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: '0 10 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: autosubmit

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: yukimaikoriya/PKUAutoSubmit-action@master
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          reason: ${{secrets.reason}}
          out_track: ${{secrets.track}}
          
