# This is a basic workflow to help you get started with Actions

name: AutoSubmit

# Controls when the action will run. 
on:
  # Uncomment following lines to schedule an auto-submit 10:00 Every day
  #schedule:
    #- cron: '0 10 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Please change this to your repo when copied
      - uses: yukimaikoriya/PKUAutoSubmit-action@master
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          reason: ${{secrets.reason}}
          out_track: ${{secrets.track}}
          
